### ISSUE TITLE
Problem of files 

### ISSUE THREAD

**Issue by Dark-Guan** [coursemdetw/project_site#1]
the .ttt files in
https://raw.githubusercontent.com/coursemdetw/project_site/gh-pages/users/g2_files/
can not be open in V-rep.
Is there some problem?

**Comment by coursemdetw** [comment]
All files should be open using V3.3.2 rev3.

**Comment by Dark-Guan** [comment]
Thanks for your apply , I have solved this problem.
Thanks again!!

**Comment by coursemdetw** [comment]
Glad to hear that, you are welcome!
